const data = {
    categories: [
        { name: "AI Writing Tools", slug: "ai-writing-tools", description: "Best AI-powered writing assistants for content, emails, and blogs." },
        { name: "AI Image Generators", slug: "ai-image-generators", description: "Top-rated AI tools for creating stunning visual art and photos." },
        { name: "AI Video Tools", slug: "ai-video-tools", description: "Professional AI tools for video editing, avatars, and generation." },
        { name: "AI Code Assistants", slug: "ai-code-assistants", description: "The best AI companions for developers and software engineers." },
        { name: "AI Chatbots", slug: "ai-chatbots", description: "Conversational AI models for research, productivity, and fun." },
        { name: "Cloud Hosting", slug: "cloud-hosting", description: "Top-rated web hosting, VPS, and cloud infrastructure providers." },
        { name: "eSIM for Travel", slug: "esim-providers", description: "Best digital SIM cards for international travelers and digital nomads." },
        { name: "SaaS Essentials", slug: "saas-essentials", description: "Critical business software, CRM, and project management tools." }
    ],
    tools: [
        // Writing
        { name: "Jasper", slug: "jasper-ai", category: "ai-writing-tools", website: "https://jasper.ai", score: 18500, featured: true },
        { name: "Grammarly", slug: "grammarly-go", category: "ai-writing-tools", website: "https://grammarly.com", score: 25400, featured: true },
        { name: "Copy.ai", slug: "copy-ai", category: "ai-writing-tools", website: "https://copy.ai", score: 12200 },
        { name: "Writesonic", slug: "writesonic", category: "ai-writing-tools", website: "https://writesonic.com", score: 9800 },
        { name: "Quillbot", slug: "quillbot", category: "ai-writing-tools", website: "https://quillbot.com", score: 15600 },
        { name: "Rytr", slug: "rytr", category: "ai-writing-tools", website: "https://rytr.me", score: 7500 },
        { name: "Anyword", slug: "anyword", category: "ai-writing-tools", website: "https://anyword.com", score: 6400 },
        { name: "Wordtune", slug: "wordtune", category: "ai-writing-tools", website: "https://wordtune.com", score: 5900 },
        { name: "Simplified", slug: "simplified", category: "ai-writing-tools", website: "https://simplified.com", score: 4800 },
        { name: "Sudowrite", slug: "sudowrite", category: "ai-writing-tools", website: "https://sudowrite.com", score: 4200 },
        { name: "Frase", slug: "frase", category: "ai-writing-tools", website: "https://frase.io", score: 3800 },
        { name: "Surfer SEO", slug: "surfer-seo", category: "ai-writing-tools", website: "https://surferseo.com", score: 3500 },
        { name: "Scalenut", slug: "scalenut", category: "ai-writing-tools", website: "https://scalenut.com", score: 3200 },
        { name: "PepperType", slug: "peppertype", category: "ai-writing-tools", website: "https://peppertype.ai", score: 2900 },
        { name: "ContentBot", slug: "contentbot", category: "ai-writing-tools", website: "https://contentbot.ai", score: 2400 },
        // Image
        { name: "Midjourney", slug: "midjourney", category: "ai-image-generators", website: "https://midjourney.com", score: 35000, featured: true },
        { name: "DALL-E 3", slug: "dalle-3", category: "ai-image-generators", website: "https://openai.com/dalle-3", score: 28000, featured: true },
        { name: "Stable Diffusion", slug: "stable-diffusion", category: "ai-image-generators", website: "https://stability.ai", score: 21000 },
        { name: "Leonardo.ai", slug: "leonardo-ai", category: "ai-image-generators", website: "https://leonardo.ai", score: 14200, featured: true },
        { name: "Adobe Firefly", slug: "adobe-firefly", category: "ai-image-generators", website: "https://adobe.com", score: 12500 },
        { name: "Canva Magic Media", slug: "canva-magic", category: "ai-image-generators", website: "https://canva.com", score: 11000 },
        { name: "BlueWillow", slug: "bluewillow", category: "ai-image-generators", website: "https://bluewillow.ai", score: 8500 },
        { name: "Playground AI", slug: "playground-ai", category: "ai-image-generators", website: "https://playgroundai.com", score: 7200 },
        { name: "Lexica", slug: "lexica", category: "ai-image-generators", website: "https://lexica.art", score: 6800 },
        { name: "DreamStudio", slug: "dreamstudio", category: "ai-image-generators", website: "https://dreamstudio.ai", score: 6200 },
        { name: "NightCafe", slug: "nightcafe", category: "ai-image-generators", website: "https://nightcafe.studio", score: 5400 },
        { name: "StarryAI", slug: "starryai", category: "ai-image-generators", website: "https://starryai.com", score: 4800 },
        { name: "Fotor AI", slug: "fotor-ai", category: "ai-image-generators", website: "https://fotor.com", score: 3900 },
        { name: "DeepAI", slug: "deepai", category: "ai-image-generators", website: "https://deepai.org", score: 3200 },
        { name: "Artbreeder", slug: "artbreeder", category: "ai-image-generators", website: "https://artbreeder.com", score: 2800 },
        // Video
        { name: "Runway", slug: "runway-gen3", category: "ai-video-tools", website: "https://runwayml.com", score: 12500, featured: true },
        { name: "Pika", slug: "pika-labs", category: "ai-video-tools", website: "https://pika.art", score: 9800, featured: true },
        { name: "HeyGen", slug: "heygen", category: "ai-video-tools", website: "https://heygen.com", score: 8400 },
        { name: "Synthesia", slug: "synthesia", category: "ai-video-tools", website: "https://synthesia.io", score: 7600 },
        { name: "InVideo AI", slug: "invideo-ai", category: "ai-video-tools", website: "https://invideo.io", score: 6200 },
        { name: "Pictory", slug: "pictory", category: "ai-video-tools", website: "https://pictory.ai", score: 5400 },
        { name: "Descript", slug: "descript", category: "ai-video-tools", website: "https://descript.com", score: 4800 },
        { name: "Kaiber", slug: "kaiber", category: "ai-video-tools", website: "https://kaiber.ai", score: 4200 },
        { name: "Lumen5", slug: "lumen5", category: "ai-video-tools", website: "https://lumen5.com", score: 3800 },
        { name: "Fliki", slug: "fliki", category: "ai-video-tools", website: "https://fliki.ai", score: 3200 },
        { name: "Elai.io", slug: "elai-io", category: "ai-video-tools", website: "https://elai.io", score: 2800 },
        { name: "Colossyan", slug: "colossyan", category: "ai-video-tools", website: "https://colossyan.com", score: 2400 },
        { name: "DeepBrain AI", slug: "deepbrain-ai", category: "ai-video-tools", website: "https://deepbrain.io", score: 2100 },
        { name: "Luma Dream Machine", slug: "luma", category: "ai-video-tools", website: "https://lumalabs.ai", score: 1800 },
        { name: "Virbo", slug: "virbo", category: "ai-video-tools", website: "https://virbo.wondershare.com", score: 1500 },
        // Code
        { name: "GitHub Copilot", slug: "github-copilot", category: "ai-code-assistants", website: "https://github.com/features/copilot", score: 42000, featured: true },
        { name: "Cursor", slug: "cursor", category: "ai-code-assistants", website: "https://cursor.com", score: 31000, featured: true },
        { name: "Tabnine", slug: "tabnine", category: "ai-code-assistants", website: "https://tabnine.com", score: 14500 },
        { name: "Amazon Q", slug: "amazon-q", category: "ai-code-assistants", website: "https://aws.amazon.com/q", score: 11000 },
        { name: "Replit Ghostwriter", slug: "replit", category: "ai-code-assistants", website: "https://replit.com", score: 9500 },
        { name: "Codeium", slug: "codeium", category: "ai-code-assistants", website: "https://codeium.com", score: 18000, featured: true },
        { name: "Sourcegraph Cody", slug: "cody", category: "ai-code-assistants", website: "https://sourcegraph.com/cody", score: 12000 },
        { name: "Blackbox AI", slug: "blackbox", category: "ai-code-assistants", website: "https://useblackbox.io", score: 8400 },
        { name: "MutableAI", slug: "mutable", category: "ai-code-assistants", website: "https://mutable.ai", score: 6200 },
        { name: "Pieces", slug: "pieces", category: "ai-code-assistants", website: "https://pieces.app", score: 5400 },
        { name: "AskCodi", slug: "askcodi", category: "ai-code-assistants", website: "https://askcodi.com", score: 4800 },
        { name: "CodePal", slug: "codepal", category: "ai-code-assistants", website: "https://codepal.ai", score: 4200 },
        { name: "Codiga", slug: "codiga", category: "ai-code-assistants", website: "https://codiga.io", score: 3800 },
        { name: "JetBrains AI", slug: "jetbrains-ai", category: "ai-code-assistants", website: "https://jetbrains.com", score: 7500 },
        { name: "Debuild", slug: "debuild", category: "ai-code-assistants", website: "https://debuild.app", score: 3100 },
        // Chatbots
        { name: "ChatGPT", slug: "chatgpt", category: "ai-chatbots", website: "https://chat.openai.com", score: 85000, featured: true },
        { name: "Claude 3", slug: "claude-ai", category: "ai-chatbots", website: "https://claude.ai", score: 62000, featured: true },
        { name: "Perplexity AI", slug: "perplexity", category: "ai-chatbots", website: "https://perplexity.ai", score: 54000, featured: true },
        { name: "Google Gemini", slug: "gemini", category: "ai-chatbots", website: "https://gemini.google.com", score: 48000 },
        { name: "Microsoft Copilot", slug: "ms-copilot", category: "ai-chatbots", website: "https://bing.com", score: 42000 },
        { name: "Poe", slug: "poe", category: "ai-chatbots", website: "https://poe.com", score: 38000 },
        { name: "Character.ai", slug: "character-ai", category: "ai-chatbots", website: "https://character.ai", score: 32000 },
        { name: "Pi", slug: "inflection-pi", category: "ai-chatbots", website: "https://inflection.ai", score: 28000 },
        { name: "HuggingChat", slug: "hugging-chat", category: "ai-chatbots", website: "https://huggingface.co/chat", score: 21000 },
        { name: "You.com", slug: "you-chat", category: "ai-chatbots", website: "https://you.com", score: 15000 },
        { name: "Phind", slug: "phind", category: "ai-chatbots", website: "https://phind.com", score: 12500 },
        { name: "ChatPDF", slug: "chatpdf", category: "ai-chatbots", website: "https://chatpdf.com", score: 11000 },
        { name: "Monica", slug: "monica", category: "ai-chatbots", website: "https://monica.im", score: 9800 },
        { name: "Merlin", slug: "merlin", category: "ai-chatbots", website: "https://getmerlin.in", score: 8400 },
        { name: "Sider", slug: "sider", category: "ai-chatbots", website: "https://sider.ai", score: 7200 },
        // Hosting
        { name: "AWS", slug: "aws", category: "cloud-hosting", website: "https://aws.amazon.com", score: 55000, featured: true },
        { name: "Google Cloud", slug: "gcp", category: "cloud-hosting", website: "https://cloud.google.com", score: 48000, featured: true },
        { name: "Azure", slug: "azure", category: "cloud-hosting", website: "https://azure.microsoft.com", score: 45000, featured: true },
        { name: "DigitalOcean", slug: "digital-ocean", category: "cloud-hosting", website: "https://digitalocean.com", score: 32000 },
        { name: "Linode", slug: "linode", category: "cloud-hosting", website: "https://linode.com", score: 21000 },
        { name: "Vercel", slug: "vercel", category: "cloud-hosting", website: "https://vercel.com", score: 28000, featured: true },
        { name: "Netlify", slug: "netlify", category: "cloud-hosting", website: "https://netlify.com", score: 24000 },
        { name: "Railway", slug: "railway", category: "cloud-hosting", website: "https://railway.app", score: 18000 },
        { name: "Fly.io", slug: "fly-io", category: "cloud-hosting", website: "https://fly.io", score: 15000 },
        { name: "Render", slug: "render", category: "cloud-hosting", website: "https://render.com", score: 12500 },
        { name: "Hetzner", slug: "hetzner", category: "cloud-hosting", website: "https://hetzner.com", score: 11000 },
        { name: "OVHcloud", slug: "ovhcloud", category: "cloud-hosting", website: "https://ovhcloud.com", score: 9800 },
        { name: "Cloudways", slug: "cloudways", category: "cloud-hosting", website: "https://cloudways.com", score: 8400 },
        { name: "Vultr", slug: "vultr", category: "cloud-hosting", website: "https://vultr.com", score: 7200 },
        { name: "Heroku", slug: "heroku", category: "cloud-hosting", website: "https://heroku.com", score: 6500 },
        // eSIM
        { name: "Airalo", slug: "airalo", category: "esim-providers", website: "https://airalo.com", score: 32000, featured: true },
        { name: "Holafly", slug: "holafly", category: "esim-providers", website: "https://holafly.com", score: 28000, featured: true },
        { name: "Nomad", slug: "nomad", category: "esim-providers", website: "https://getnomad.app", score: 18000 },
        { name: "AloSIM", slug: "alosim", category: "esim-providers", website: "https://alosim.com", score: 14500 },
        { name: "Yesim", slug: "yesim", category: "esim-providers", website: "https://yesim.app", score: 11000 },
        { name: "Ubigi", slug: "ubigi", category: "esim-providers", website: "https://ubigi.com", score: 9500 },
        { name: "Maya Mobile", slug: "maya-mobile", category: "esim-providers", website: "https://maya.net", score: 8400 },
        { name: "SimOptions", slug: "simoptions", category: "esim-providers", website: "https://simoptions.com", score: 7200 },
        { name: "Saily", slug: "saily", category: "esim-providers", website: "https://saily.com", score: 6800 },
        { name: "GigSky", slug: "gigsky", category: "esim-providers", website: "https://gigsky.com", score: 6200 },
        { name: "BetterRoaming", slug: "better-roaming", category: "esim-providers", website: "https://betterroaming.com", score: 5400 },
        { name: "BNESIM", slug: "bnesim", category: "esim-providers", website: "https://bnesim.com", score: 4800 },
        { name: "MobiMatter", slug: "mobimatter", category: "esim-providers", website: "https://mobimatter.com", score: 4200 },
        { name: "Airhub", slug: "airhub", category: "esim-providers", website: "https://airhubapp.com", score: 3800 },
        { name: "GlobaleSIM", slug: "global-esim", category: "esim-providers", website: "https://globalesim.app", score: 3100 },
        // SaaS
        { name: "Notion", slug: "notion", category: "saas-essentials", website: "https://notion.so", score: 55000, featured: true },
        { name: "Slack", slug: "slack", category: "saas-essentials", website: "https://slack.com", score: 48000, featured: true },
        { name: "Loom", slug: "loom", category: "saas-essentials", website: "https://loom.com", score: 32000, featured: true },
        { name: "Linear", slug: "linear", category: "saas-essentials", website: "https://linear.app", score: 28000 },
        { name: "Framer", slug: "framer", category: "saas-essentials", website: "https://framer.com", score: 21000 },
        { name: "Webflow", slug: "webflow", category: "saas-essentials", website: "https://webflow.com", score: 24000, featured: true },
        { name: "Stripe", slug: "stripe", category: "saas-essentials", website: "https://stripe.com", score: 42000, featured: true },
        { name: "Intercom", slug: "intercom", category: "saas-essentials", website: "https://intercom.com", score: 18000 },
        { name: "Zoom", slug: "zoom", category: "saas-essentials", website: "https://zoom.us", score: 38000 },
        { name: "Miro", slug: "miro", category: "saas-essentials", website: "https://miro.com", score: 15000 },
        { name: "Calendly", slug: "calendly", category: "saas-essentials", website: "https://calendly.com", score: 12500 },
        { name: "HubSpot", slug: "hubspot", category: "saas-essentials", website: "https://hubspot.com", score: 21000 },
        { name: "Salesforce", slug: "salesforce", category: "saas-essentials", website: "https://salesforce.com", score: 45000 },
        { name: "Zapier", slug: "zapier", category: "saas-essentials", website: "https://zapier.com", score: 11000 },
        { name: "Make", slug: "make", category: "saas-essentials", website: "https://make.com", score: 9200 }
    ]
};

module.exports = data;
