
-- 1. Add view_count to articles table (if not exists)
ALTER TABLE articles ADD COLUMN IF NOT EXISTS view_count INTEGER DEFAULT 0;

-- 2. Create article_views table for detailed tracking
CREATE TABLE IF NOT EXISTS article_views (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id UUID REFERENCES articles(id) ON DELETE CASCADE,
    session_id TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create index for faster querying
CREATE INDEX IF NOT EXISTS idx_article_views_article_id ON article_views(article_id);
CREATE INDEX IF NOT EXISTS idx_article_views_created_at ON article_views(created_at);

-- 4. Create function to increment view count
CREATE OR REPLACE FUNCTION increment_article_view(article_row_id UUID)
RETURNS VOID AS $$
BEGIN
    UPDATE articles
    SET view_count = COALESCE(view_count, 0) + 1
    WHERE id = article_row_id;
END;
$$ LANGUAGE plpgsql;

-- 5. Add submitter_email to items table for feedback loop
ALTER TABLE items ADD COLUMN IF NOT EXISTS submitter_email TEXT;
